version: "3.9"
services:
  nextjs:
    container_name: nextjs
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nestjs
  nestjs:
    container_name: nestjs
    restart: always
    hostname: nestjs
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    restart: always
    hostname: mysql
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    env_file:
      - ./server/.env
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: {}